#!/usr/bin/env python3
"""Build public/sitemap.xml from the pages themselves.

The sitemap and the rel="canonical" in each page's head are two statements
about the same thing, and when they disagree a crawler has to pick one. The
old file said so in a comment and then drifted anyway: it mixed .html and
extensionless spellings, listed eleven retired pages, and listed the privacy,
terms and cookies pages that carry noindex.

So the sitemap is no longer written by hand. Every page declares its own
canonical URL; this reads them and lists the ones that should be there. A page
is included when:

  * it carries rel="canonical" pointing at itself, and
  * it does not carry noindex.

A page whose canonical points somewhere else is a retired page that has been
folded into another, and belongs in the sitemap no more than a redirect does.
404.html is excluded for the obvious reason, and style-guide.html excludes
itself by carrying noindex.

lastmod is the file's own last commit date, which is true by construction and
does not need remembering. The one exception is a commit that touches every
page without changing what any of them says -- a script tag added site-wide,
say. Dating all 67 pages to that day would tell Google every page had changed
when none had, and a lastmod that cries wolf is one Google learns to ignore.
Such a commit carries the line

    Sitemap-lastmod: unchanged

in its message, and is passed over when a page is dated.

priority and changefreq are not emitted: Google has said for years that it
ignores both, and a number nobody reads is a number that goes stale.

Usage:
    python scripts/update-sitemap.py            # write it
    python scripts/update-sitemap.py --check    # fail if it is out of date
"""
import io
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC = os.path.join(ROOT, "public")
OUT = os.path.join(PUBLIC, "sitemap.xml")
HOST = "https://cedarhollow.uk"
SKIP_FILES = {"404.html"}

# Webflow writes href before rel, the newer pages the other way round, so the
# tag is found first and its href read second rather than assuming an order.
CANON_TAG_RE = re.compile(r'<link[^>]*rel="canonical"[^>]*>', re.I)
HREF_RE = re.compile(r'href="([^"]+)"', re.I)
ROBOTS_RE = re.compile(r'<meta[^>]*name="robots"[^>]*content="([^"]*)"', re.I)


def pages():
    for base, _dirs, files in os.walk(PUBLIC):
        for name in sorted(files):
            if name.endswith(".html"):
                yield os.path.join(base, name)


def rel_url(path):
    """The canonical spelling of a file's own URL, both ways round.

    A page may canonicalise to /oxford or to /oxford.html; either is a claim
    about itself, so both count as pointing at itself.
    """
    rel = os.path.relpath(path, PUBLIC).replace(os.sep, "/")
    if rel == "index.html":
        return {HOST + "/", HOST, HOST + "/index.html"}
    return {HOST + "/" + rel, HOST + "/" + rel[:-5]}


def last_commit(path):
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%ad", "--date=short", "--invert-grep",
             "--grep=^Sitemap-lastmod: unchanged$", "--", path],
            cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
        return out or None
    except Exception:
        return None


def collect():
    listed, skipped = [], []
    for path in pages():
        rel = os.path.relpath(path, PUBLIC).replace(os.sep, "/")
        if rel in SKIP_FILES:
            skipped.append((rel, "excluded by name"))
            continue
        html = io.open(path, encoding="utf-8", errors="replace").read()

        robots = ROBOTS_RE.search(html)
        if robots and "noindex" in robots.group(1).lower():
            skipped.append((rel, "noindex"))
            continue

        tag = CANON_TAG_RE.search(html)
        href_m = HREF_RE.search(tag.group(0)) if tag else None
        if not href_m:
            skipped.append((rel, "no canonical"))
            continue

        href = href_m.group(1).rstrip("/") or HOST
        if href not in {u.rstrip("/") or HOST for u in rel_url(path)}:
            skipped.append((rel, "canonical -> " + href.replace(HOST, "")))
            continue

        listed.append((href_m.group(1), last_commit(path), rel))
    listed.sort(key=lambda r: r[2])
    return listed, skipped


def build(listed):
    out = ['<?xml version="1.0" encoding="UTF-8"?>']
    out.append("<!-- Generated by scripts/update-sitemap.py; do not edit by hand.")
    out.append("     Each <loc> is the page's own rel=\"canonical\", read from the page,")
    out.append("     so the two can never contradict each other. Pages that carry noindex,")
    out.append("     and pages whose canonical points at another page because they have")
    out.append("     been folded into it, are left out. -->")
    out.append('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    for loc, mod, _rel in listed:
        out.append("  <url>")
        out.append("    <loc>%s</loc>" % loc)
        if mod:
            out.append("    <lastmod>%s</lastmod>" % mod)
        out.append("  </url>")
    out.append("</urlset>")
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv
    listed, skipped = collect()
    xml = build(listed)

    current = io.open(OUT, encoding="utf-8", newline="").read() if os.path.exists(OUT) else ""
    if check:
        if current.replace("\r\n", "\n") != xml:
            sys.exit("sitemap.xml is out of date; run scripts/update-sitemap.py")
        print("sitemap.xml is up to date (%d urls)" % len(listed))
        return

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(xml)
    print("sitemap.xml: %d urls" % len(listed))
    print("left out (%d):" % len(skipped))
    for rel, why in skipped:
        print("   %-38s %s" % (rel, why))


if __name__ == "__main__":
    main()
